<?php
/**
 * Copyright (c) 2022-2024 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// @codingStandardsIgnoreFile
/* @var Mastercard\Mastercard\Block\ClearCheckoutData $block */

$paymentMethod = $block->getPaymentMethodCode();
$targetMethod = 'tns_hosted';

if ($paymentMethod === $targetMethod): ?>

<script type="text/javascript">
    require(['domReady!'], function () {
          const storageKey = 'mage-cache-storage';

           let cache = JSON.parse(localStorage.getItem(storageKey) || '{}');

        if (cache['checkout-data']) {
         const keysToDelete = [
                'billingAddressFromData',
                'shippingAddressFromData',
                'selectedPaymentMethod',
                'selectedShippingRate',
                'inputFieldEmailValue'
            ];
            keysToDelete.forEach(key => {
                delete cache['checkout-data'][key];
            });

            localStorage.setItem(storageKey, JSON.stringify(cache));
        }
       
    });
</script>
<?php endif; ?>
